@extends('fe.master')
@section('navbar')
    @include('fe.navbar')
@endsection
@section('carousel')
    @include('fe.carousel')
@endsection
@section('about')
    @include('fe.about')
@endsection
@section('feature')
    @include('fe.feature')
@endsection
@section('product')
    @include('fe.product')
@endsection
@section('visit')
    @include('fe.visit')
@endsection
@section('testimonial')
    @include('fe.testimonial')
@endsection
@section('footer')
    @include('fe.footer')
@endsection